--- 
spring: 
  profiles: cloud
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://morgan:morgan@eureka-mas.cfapps.io/eureka
  instance: 
    hostname: "${vcap.application.uris[0]}"
    nonSecurePort: 80
