---
spring:
  jpa:
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 
---
spring:
  profiles: local
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/company
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    
---
spring:
    profiles: cloud
    
message: Morgan Wrote it
eureka:
 client:
   serviceUrl:
     defaultZone: http://morgan:morgan@{https://eureka-mas.cfapps.io/eureka

