---
spring:
  cloud:
    config:
      server:
        port: 8101
        git:
          uri: ${vcap.services.config-server.credentials.uri}     
          
security:
  user:
    name:  ${vcap.services.config-basic-auth.credentials.username}
    password:  ${vcap.services.config-basic-auth.credentials.password}
---
spring:
   profiles:cloud

message: attendees
