---
spring:
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.config-server-uri.credentials.uri}     
          
security:
  user:
    username:  ${vcap.services.config-basic-auth.credentials.username:morgan}
    password:  ${vcap.services.config-basic-auth.credentials.password:morgan}

spring:
   profiles cloud

message: eureka Message
