---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL

endpoints:
  sensitive: false
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.config-server-uri.credentials.uri}     
          
security:
  user:
    name:  ${vcap.services.config-basic-auth.credentials.username}
    password:  ${vcap.services.config-basic-auth.credentials.password}
